### ISSUE TITLE
Refactoring should not cause a script failure

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-js#104]
**Actual behavior**
The parameter name generated after refactoring takes the value given in the text as the parameter name. This causes compilation errors sometimes

**Steps to replicate**
* In a `gauge-js` project
* Refactor `Vowels in English language are "aeiou"` to `Vowels in English language are "aeiou" something else "" and "ddd"`
* Another example refactor `something` to `somethingword "3" has "3" vowels`
Goto the implementation files and see the script errors

**Version**
```
Gauge version: 0.9.8.nightly-2018-01-30
Commit Hash: 2ed02d8

Plugins
-------
js (2.1.1.nightly-2018-01-16)
```
getgauge/gauge-vscode#81

**Comment by sguptatw** [comment]
The following scenario is out of scope.
**Out of scope**
Removing an old parameter/Changing the value of the parameters changes the variable name in the signature. This is okay, 'cause it is not stopping the user from proceeding with other actions.

**Comment by nehashri** [comment]
fix should be available in nightly >= 14-2-2018

**Comment by sguptatw** [comment]
Blocked 'cause of https://github.com/getgauge/gauge/issues/943

**Comment by sguptatw** [comment]
Refactor `something` to `somethingword "3" has "3"`. This creates parameters with the same name.
In a spec, this now appears as an unimplemented step. 
When I correct the parameter name the usage statistics is corrected and the step shows as implemented.

**Comment by BugDiver** [comment]
Discussed with @nehashri. Currently, we will not be handling the issue with the same parameter name in step annotations. 
The parameters name collision in the implementation function will be handled.
The PR is created in respective languages.
* Python getgauge/gauge-python#77
* JS  getgauge/gauge-js#148

**Comment by BugDiver** [comment]
The fix should be available in nightlies >23-05-2018
