### ISSUE TITLE
Failed to read execution status

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-js#109]
_From @sguptatw on February 15, 2018 5:56_

**Expected behavior**
Should be able to execute specs

**Actual behavior**
```
[Error - 11:20:58] Failed to read execution status information. Reason: File /Users/sswaroop/work/python/basic/.gauge/executionStatus.json doesn't exist.
[Info  - 11:20:58] Connection to server got closed. Server will restart.
```

**Steps to replicate**
* Create a new js project
* Open the project
* Run all specifications

**Version**
```
Gauge version: 0.9.8.nightly-2018-02-13
Commit Hash: 7d3dc0a

Plugins
-------
python (0.2.4.nightly-2018-02-11)
```

_Copied from original issue: getgauge/gauge-python#29_

**Comment by sguptatw** [comment]
_From @riju91 on February 16, 2018 5:52_

Could not reproduce this issue on latest nightly, both gauge and gauge-python on windows and mac. Can you please try it once and confirm @sguptatw ?

**Comment by sguptatw** [comment]
This is still repliable on Mac OS in js project

**Comment by Apoorva-GA** [comment]
Works fine on mac with js project as well.
