### ISSUE TITLE
The generated annotation text should not have issues

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-js#110]
**Actual behavior**
The annotation text parameters are generated with the values of the steps causing a few issues

**Steps to replicate**
* Refactor a step to something with
- parameter where value is empty
- parameters with the same value
- param value `a step with "<file:somthing>"`

**Version**
```
Gauge version: 0.9.8.nightly-2018-02-18
Commit Hash: 7acf174

Plugins
-------
js (2.1.1.nightly-2018-02-14)
```

**Comment by sguptatw** [comment]
The behavior should be similar to what generate stub implementation does

Refactor `a step` to `a step with "<file:somthing>"` should give annotation text as `a step with <arg0>`

**Comment by BugDiver** [comment]
fix should be availabe in nightly >= 23-05-2018
