### ISSUE TITLE
Skeleton files and templates are out of sync

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-js#112]
The skeleton files for js uses the old style of specifying steps.

```
gauge.step("Vowels in English language are <vowels>.", function(vowelsGiven) {
  assert.equal(vowelsGiven, vowels.join(""));
});
```

Update these to

```
step("Vowels in English language are <vowels>.", function(vowelsGiven) {
  assert.equal(vowelsGiven, vowels.join(""));
});
```

**Comment by BugDiver** [comment]
`gauge` tries to initialize a project using templates. If it is not able to do so It creates project using `skeleton`  files.
To reproduce ant test this issue disconnect internet.

**Comment by BugDiver** [comment]
Fix should be available in `gauge-js` nightly >= 27-02-2018

**Comment by sguptatw** [comment]
The documentation examples https://getgauge.github.io/gauge-js/syntax/step-implementation.html still have gauge.step instead of step.

>Note: Hooks also have the gauge.<hookname> in documentation

**Comment by sguptatw** [comment]
`gauge init js` offline is working as expected.

However, the documentation should be updated with the changes - https://github.com/getgauge/gauge-js/issues/117
