### ISSUE TITLE
Screenshot is not captured on failure

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-js#116]
**Expected behavior**
Should capture screenshot when a test fails

**Actual behavior**
Not capturing the screenshot when there is a failure.

**Steps to replicate**
* Create a new `gauge-js` project
* Update the example 
```
# Specification Heading

   |something|
   |---------|
   |abc      |
   |def      |

* Vowels in English language are <something>.

## Vowel counts in single word

tags: single word

* The word "gauge" has "3" vowels.

## Vowel counts in multiple word

This is the second scenario in this specification

Here's a step that takes a table

* Almost all words have vowels 

   |Word  |Vowel Count|
   |------|-----------|
   |Gauge |3          |
   |Mingle|2          |
   |Snap  |1          |
   |GoCD  |1          |
   |Rhythm|0          |

___
* teardown
```
* Run the specs
* Screenshot is not captured on failure. Getting the following error
```
Error: spawnSync gauge_screenshot ENOENT
```
> Note: When the same spec is used for a `gauge-java` project, the screenshot is captured. But the screenshot plugin is not installed

**Version**
```
Gauge version: 0.9.8.nightly-2018-02-26
Commit Hash: 77c642d

Plugins
-------
dotnet (0.0.1.nightly-2018-02-14)
html-report (4.0.4.nightly-2018-01-11)
java (0.6.7.nightly-2018-02-23)
js (2.1.1.nightly-2018-02-27)
python (0.2.4.nightly-2018-02-27)
ruby (0.4.3.nightly-2018-02-13)
spectacle (0.1.3.nightly-2017-10-26)
```

**Comment by nehashri** [comment]
Gauge screenshot plugin is not available on nightly channel. That is why gauge-js failed to take screenshot. gauge-java uses its custom libraries to take screenshot, hence that did not fail.
Switching to default gauge_repository_url fixes the issue.

**Comment by sguptatw** [comment]
This happens on `gauge_repository_url` - https://downloads.getgauge.io/templates
**Version**
```
Gauge version: 0.9.8.nightly-2018-03-14
Commit Hash: 0ac4700

Plugins
-------
html-report (4.0.4.nightly-2018-03-20)
js (2.2.0.nightly-2018-03-19)
```
**Steps to replicate**
* Create a gauge-js project
* Make a step fail
* Run the specs
> Observe error `Error: spawnSync gauge_screenshot ENOENT`

**Comment by sriv** [comment]
@sguptatw the correct value should be

```
gauge_repository_url            https://downloads.gauge.org/plugin
```

or 

```
gauge_repository_url            https://downloads.getgauge.io/plugin
```

Your report seems to suggest that you have `/templates` instead of `/plugin`. Please check.

**Comment by sguptatw** [comment]
Yes, the configuration was wrong.
Working as expected
