### ISSUE TITLE
Sandbox missing expected globals

### ISSUE THREAD

**Issue by mpareja** [getgauge/gauge-js#132]
The [sandbox created](https://github.com/getgauge/gauge-js/blob/850ae0c2a843b660a68766e47ca337a6a5d200d4/src/vm.js#L28) when loading test files is [missing several node.js globals](https://nodejs.org/api/globals.html). From what I can tell, we're missing at least:

  + `__dirname`
  + `__filename`
  + `clearImmediate`
  + `setImmediate`

### Reproduction

1. Write a test which references `__dirname`
2. Run the tests

#### Unexpected

`ReferenceError: __dirname is not defined`

#### Expected

`__dirname` returns the directory of the current module

**Comment by mpareja** [comment]
I'll put together a pull request for this.

**Comment by nehashri** [comment]
Card need to be verified by QA
