### ISSUE TITLE
Should capture screenshot when `throw 'something'` is used

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-js#134]
**Expected behavior**
If there is a failure, screenshot should be captured

**Actual behavior**
If an error is `throw 'something'` is used, the screenshot is not getting captured

**Steps to replicate**
* `gauge init js`
* In a step `throw 'something'`
> Screenshot is not captured

**Version**
```
Gauge version: 0.9.8.nightly-2018-03-28
Commit Hash: 901e659

Plugins
-------
html-report (4.0.4.nightly-2018-03-28)
js (2.2.0.nightly-2018-03-28)
screenshot (0.0.1)
```

**Comment by nehashri** [comment]
Throwing strings instead of Error objects is not a good practice. 
Javascript may allow us to capture non Errors too, but this practice is not encouraged. Should we really be trying to fix this?
