### ISSUE TITLE
Error details not displayed for subsequent steps when there is a continue on failure

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-js#135]
**Expected behavior**
Should be able to see the error details and screenshot for all failures

**Actual behavior**
When continue on failure is used, the details are missing for the subsequent steps

**Steps to replicate**
* Create a `gauge-js` project
* Add `continueOnFailure` for step1
* Add failures in step1 and step2
* run the specs
* Open the html-report
> The details are not shown for subsequent steps

**Version**
```
Gauge version: 0.9.8.nightly-2018-03-28
Commit Hash: 901e659

Plugins
-------
html-report (4.0.4.nightly-2018-03-28)
js (2.2.0.nightly-2018-03-28)
```

**Comment by shubhamsc** [comment]
it seems to be working fine for a example project. Please verify again.

**Comment by Apoorva-GA** [comment]
Not replicable on linux. Hence closing the issue.
