### ISSUE TITLE
File name of the file names generated should be consistent

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-js#146]
**Expected behavior**
The generated file names should be consistent

**Actual behavior**
The step implementation file name is different when it is generated from `init` and `create step implementation`

**Steps to replicate**
* Create a `gauge-js` project
> This creates a `step_implementation.js` file
* Generate a step implementation
> The creates a `step-implementation.js` file

The generated name should be consistent

**Version**
```
Gauge version: 0.9.9.nightly-2018-05-15
Commit Hash: 8db625f

Plugins
-------
js (2.3.1.nightly-2018-05-08)
```

**Comment by NivedhaSenthil** [comment]
fix should be available in nightly >= 13/06/2018

**Comment by sguptatw** [comment]
The new file created has `-number` suffixed to it

**Expected behavior**
The naming convention of the language should be followed. 

**Actual behavior**
If a file `step_implementation.js` is already present. The newly generated file's name is `step-implementation-1.js` 

**Steps to replicate**
* Create a new `gauge-js` project
* Add a new step
* Implement it in a new file. 
> The generated name has `-`.

**Comment by sguptatw** [comment]
The new file created has `-number` suffixed to it

**Expected behavior**
The naming convention of the language should be followed. 

**Actual behavior**
If a file `step_implementation.js` is already present. The newly generated file's name is `step_implementation-1.js` 

**Steps to replicate**
* Create a new `gauge-js` project
* Add a new step
* Implement it in a new file. 
> The generated name has `-`.

**Verified on**
```
Gauge version: 0.9.9.nightly-2018-06-01
Commit Hash: 812f26e

Plugins
-------
js (2.3.1.nightly-2018-06-13)
```

**Comment by NivedhaSenthil** [comment]
Fix should be available in nightly >= 14/06/2018
