### ISSUE TITLE
Should be able to add parameters before and after existing parameters

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-js#151]
**Actual behavior**
The generated parameter names are repeated

**Steps to replicate**
* Create a new `gauge-js` project
* Create a new step with no params `a new step`
* Refactor to add one parameter `a new step with one param "param"`
* Refactor again to add a parameter before the existing parameter `a new step "before" param and "param"`
> The step is shown as unimplemented. See the implementation file the parameter name is repeated
Reloading the project shows all steps as unimplemented
**Version**
```
Gauge version: 0.9.9.nightly-2018-05-23
Commit Hash: cf46420

Plugins
-------
js (2.3.1.nightly-2018-05-23)
```
> Observed on Windows

Related to https://github.com/getgauge/gauge-js/issues/104

**Comment by sguptatw** [comment]
The usage statistics of this step is shown as `0`
Related to https://github.com/getgauge/gauge-python/issues/31

**Comment by BugDiver** [comment]
The Fix should be availabe in nightly >= 018-05-24
