### ISSUE TITLE
Step annotation should not have placeholder names as values

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-js#152]
**Expected behavior**
When a step with no parameters is refactored to have a parameter, the annotation text placeholders should be independent of the value

**Actual behavior**
The annotation parameter name generated is the value itself

**Steps to replicate**
* Create a `gauge-js` project
* Create a step `a step with no parameters`
* Rename it to `a step with parameters <~!@#$%^&*()_++-~>` 
> The implementation file now has the annotation text placeholder with the value

**Version**
```
Gauge version: 0.9.9.nightly-2018-05-23
Commit Hash: cf46420

Plugins
-------
js (2.3.1.nightly-2018-05-23)
```
Related to https://github.com/getgauge/gauge-js/issues/110

**Comment by BugDiver** [comment]
Since this doesn't break any user flow, It has been deprioritized.

**Comment by zabil** [comment]
Closing this as Gauge will not fixing this.
