### ISSUE TITLE
Refactoring a concept with a file parameter is replacing the contents of the file as placeholder name

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-js#155]
**Expected behavior**
The placeholder name should be independent of the value

**Actual behavior**
It is being replaced with the value

**Steps to replicate**
* Create a file 'something.txt`
```
sfsdf
sdfsdf
sdfsdf
```
* Create a new concept with `a new concept`
* Refactor the concept to `a new concept <file:... the new file>
> The concept name now has the contents of the file

This is applicable to any value being passed.
The value name should not be used

**Version**
```
Gauge version: 0.9.9.nightly-2018-05-24
Commit Hash: 2150e31

Plugins
-------
js (2.3.1.nightly-2018-05-24)
```

**Comment by shubhamsc** [comment]
This issue was moved to getgauge/gauge#1063
