### ISSUE TITLE
Should be able to configure the implementation directory

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-js#157]
**Proposed behavior**
An env configuration to specify the implementation directory STEP_IMPL_DIR

**Current behavior**
The default is `tests`

**Version**
```
Gauge version: 0.9.9.nightly-2018-05-29
Commit Hash: 1a15b83

Plugins
-------
js (2.3.1.nightly-2018-05-24)
```

**Comment by nehashri** [comment]
There is already a environment variable `STEP_IMPL_DIR` which takes a comma separated list of implementation directories. If the variable is not specified, it is defaulted to `tests`.
Is there something else you are looking for?

**Comment by sguptatw** [comment]
A Clarification -
Is this a language specific feature/ something that can be available across languages? So, when steps are implemented in VSCode, it should give an option of select among the directories mentioned in STEP_IMPL_DIR.
Currently the step is implemented in the first directory of STEP_IMPL_DIR.

- [ ] When gauge-js project is initialized, this property should be available with default value set. Currently it when gauge-python project is initialized it is available in python.properties and is also documented. w.r.t gauge-js I felt this option should be discoverable by user.

**Comment by nehashri** [comment]
> Is this a language specific feature/ something that can be available across languages?

This is not available in all the languages. The option

> So, when steps are implemented in VSCode, it should give an option of select among the directories mentioned in STEP_IMPL_DIR.

This needs a change in VSCode.

> When gauge-js project is initialized, this property should be available with default value set. 

The property has been added to all js and python templates.

**Comment by sguptatw** [comment]
- [x] The template has the property.
- [x] After reload, All the implementation files from all source directories (STEP_IMPL_DIR) are listed.
> Options for other languages are being tracked separately
