### ISSUE TITLE
Support async custom screenshot functions

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-js#165]
### Current behavior

Screenshot functionality in drivers like taiko, webdriver and puppeteer is captured asynchronously however gauge's custom screenshot does not support asynchronous functions

For e.g. with taiko
```
gauge.screenshotFn = async function () {
    return "base64encoding";
};
```
 or 

```
gauge.screenshotFn = async function () {
    return await screenshot();
};
```

and the using it

```
step("Go to Gauge homepage at <query>", async function (query) {
    await goto(query);
    gauge.screenshot();
});
```

The screenshots don't appear in the report.

### Expected behavior

Support `async` functions

**Comment by sguptatw** [comment]
Taiko getting capturing an empty screenshot is tracked as a part of https://github.com/getgauge/taiko/issues/114
