### ISSUE TITLE
Using Gauge along with Babel transpiler

### ISSUE THREAD

**Issue by fwouts** [getgauge/gauge-js#168]
First off, thanks for building and maintaining Gauge!

We're using [Babel](https://babeljs.io/) in our codebase, as it lets us use modern JavaScript features such as ES6 modules (`import` and `export` keywords) without worrying about compatibility with older web browsers as well as Node.

I couldn't find a way to also use the Babel transpiler with the Gauge JS plugin. This means that we now have two separate styles in our codebase:
- "normal" code uses `import fetch from "node-fetch"` and `export class ...`
- "gauge" code uses `const fetch = require("node-fetch")` and `module.exports = class ...`

Is this something you've considered?

I'm happy to try and send a PR with a bit of guidance about where it would fit in the codebase :)

**Comment by shubhamsc** [comment]
currently, gauge doesn't support es6 syntax for implementing step. you can use babel transpiler to convert your es6 code to simple js

**Comment by shubhamsc** [comment]
Gauge doesn't support es6 syntax for step implementation at the moment.
You can write tests in es6 syntax and compile it with babel and Gauge can use its output to run the tests. You will need to set `STEP_IMPL_DIR` environment variable to babel's output directory.

Let us know if you think this can be handled in a different manner. Any contributions are always welcome and we would be happy to help you. You can reach out to us here or in [gitter](https://gitter.im/getgauge/chat)

**Comment by fwouts** [comment]
Thank you Shubham.

Compiling our tests with Babel and then setting `STEP_IMPL_DIR` to the output directory would be an OK approach, but it's an extra step in the process and it means a developer couldn't simply run `gauge` to execute their tests. It's therefore not ideal.

Given how common Babel is in the JavaScript ecosystem, it would be nice if Gauge could automatically detect a `.babelrc` configuration and use it to automatically transpile the code. This could be done in a few ways:
- automatically transpiling any source file with [`babel-core`](https://www.npmjs.com/package/babel-core)
- using `babel-node` instead of `node` to run test steps

Related note: as a first step to try and implement this, I tried adding a test in `vm-test.js` with the following code:
```

    it("import", function() {
      var vm = new VM();
      vm.contextify();
      assert.doesNotThrow(function() {
        vm.run(`import * as fs from "fs";`);
      });
    });
```
Surprisingly, the test passes, I guess because it fails on a separate thread or process?

**Comment by sriv** [comment]
Hi @fwouts , thank you for the kind words!

Generally speaking, we have been trying to keep Gauge agnostic of frameworks. However, something like babel is very commonly used, as you pointed out.

Thinking out aloud here:

- make the node runtime and the flags configurable. ex. `package.json` could have something like
```
"gauge" : {
  "node_bin_path": "path_to_specific_node_bin",
  "node_bin_args": "--harmony",
}
```
- additionally, add transpiling/compiling support by scanning `build` script in `package.json`. ex:
```
"scripts" :{
  "build": "tsc ./...", 
  "test": "gauge run specs",
}
```

The only catch with pre-compiling/transpiling is that it will break the authoring flow. i.e. if you use gauge-vscode and try to navigate to a definition of a step, it will take you to the generated code, rather than the original authored code. That would be bad for editing.

**Comment by fwouts** [comment]
Thanks @sriv.

I think the first option of being able to set the Node flag `--harmony` would already be a solid first step, whether Babel support is later added or not.

Another option could be to do the transpiling directly when we load JS implementation files, for example in [vm.js](https://github.com/getgauge/gauge-js/blob/master/src/vm.js). I think this may require a bit of refactoring though, as right now only that specific file we're executing would be transpiled, but not other files that it imports (I could be misunderstanding how it all works).

**Comment by sguptatw** [comment]
The last commit is on `13-9-2018` and the available gauge-js nightly is `13-9-2018`. Are the required changes available? Es6 syntax is not recognized. 

**Steps to replicate**
* `npm test` on the following gauge-project 
> `--harmony` set in the default properties.

[gauge-babel-example.zip](https://github.com/getgauge/gauge-js/files/2387590/gauge-babel-example.zip)

**Comment by sriv** [comment]
I can see that my changes are merged. let me have a look to see if this needs more work.

**Comment by sguptatw** [comment]
Passing argument to the node runner is done - https://github.com/getgauge/gauge-js/issues/171

However there is more work to be done for Babel support. So moving the card back to triage.

**Comment by advait012** [comment]
When I am using babel core to compile the step implementation , It is compiling the step implementation to output folder smoothly.But when I tried to run the spec I am getting the error : "Duplicate Step Implementation found".
How can I get rid of this error ?

Note : I have already configured output folder in Step_imp_Dir variable in properties file

**Comment by zabil** [comment]
As this depends on a lot of things like configurations, folder structure etc. Can you please share a sample project where someone can replicate this problem? Preferably a GitHub repo.

**Comment by zabil** [comment]
Closing this as Gauge now has Typescript which a good balance of ES6 features and type safety.
