### ISSUE TITLE
Should be able to run js project without package.json

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-js#176]
**Expected behavior**
Should be able to run js project without package.json

**Actual behavior**
Getting the error
```
(node:33976) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
{ Error: ENOENT: no such file or directory, open '...\js_new_proj1\package.json'
    at Object.fs.openSync (fs.js:545:3)
    at Object.fs.readFileSync (fs.js:451:33)
    at getProjectInfo (...\AppData\Roaming\gauge\plugins\js\2.3.4.nightly-2018-11-29\src\tracker.js:14:17)
    at getPostData (...\AppData\Roaming\gauge\plugins\js\2.3.4.nightly-2018-11-29\src\tracker.js:19:12)
    at send (...\AppData\Roaming\gauge\plugins\js\2.3.4.nightly-2018-11-29\src\tracker.js:48:14)
    at Object.trackConsole (...\AppData\Roaming\gauge\plugins\js\2.3.4.nightly-2018-11-29\src\tracker.js:61:38)
    at ...\AppData\Roaming\gauge\plugins\js\2.3.4.nightly-2018-11-29\src\gauge.js:41:15
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: '...\\js_new_proj1\\package.json' }
```

**Steps to replicate**
* Ensure network is disconnected
* Create a gauge-js project `gauge init js`
* Run gauge `gauge run`
> Observe the above error occurs

**Version**
```
Gauge version: 1.0.4.nightly-2018-11-26
Commit Hash: f6cb60c

Plugins
-------
js (2.3.4.nightly-2018-11-29)
```

**Comment by shubhamsc** [comment]
@sguptatw I'm unable to replicate above issue. I followed the same steps.
 It works fine for me with a deprecation warning.
`(node:33976) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead`

We are using taiko as dependency to running js test. For that we need package.json file to install taiko locally.

**Comment by sguptatw** [comment]
@shubhamsc Did you `Ensure network is disconnected`? 'Cause with this it does not initiate a taiko project. It is just a js vanilla project and that is when the issue is occurring.

**Comment by shubhamsc** [comment]
@sguptatw Sorry my bad. Network is not disconnected.
But still i'm not seeing any error. it's working as expected.

**Comment by sguptatw** [comment]
@shubhamsc I have observed this on Windows. Can you check on Windows please.

**Comment by shubhamsc** [comment]
@sguptatw 
yeah, It's working fine with Mac. but Windows it is replicable.
