### ISSUE TITLE
Screenshot not available for step failure

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-js#177]
**Expected behavior**
Screenshot should be available for step failure

**Actual behavior**
Screenshot not available for step failure

**Steps to replicate**
* Create a `gauge-js` project
* Change the step_implementation.js to
```
/* globals gauge*/
"use strict";
const { openBrowser,write, closeBrowser, goto, press,text, contains } = require('taiko');
const assert = require("assert");
const headless = process.env.headless_chrome.toLowerCase() == 'true' ? true : false;

// beforeSuite(async () => openBrowser({ headless: headless }));

// afterSuite(async () => closeBrowser());

// step("Goto Google's search page", async () => goto('http://google.com'));

// step("Search for <query>", async (query) => {
//     await write(query);
//     await press('Enter');
// })

// step("Page contains <content>", async (content) => {
//     assert.equal('Exists', (await text(contains(content)).exists()).description);
// });


step("failing step", async function() {
	throw 'Unimplemented Step';
});
```
* Change the example.spec to 
```
# Getting Started with Gauge

## Search Google

* failing step
```
* Run Scenario from IDE
* Open the report
> This does not show the screenshot

**Comment by shubhamsc** [comment]
> step("failing step", async function() {
	throw 'Unimplemented Step';
});

@sguptatw  It is an unimplemented step, not exaclty failing step. We are not taking screenshot for unimplemented steps. It's not depend on IDE or Console.

**Comment by sguptatw** [comment]
@shubhamsc It is not an unimplemented step.It has an implementation that throws an exception. The exception just has the wordings `Unimplemented Step`.

**Comment by shubhamsc** [comment]
> step("failing step", async function() {
throw 'Unimplemented Step';
});

In this step implementation, we just throwing string which has the error message but does not have any stacktrace. In report generation, we first check errors and stacktrace then display any screenshot.
So, we need to change default code stubs something similar to this:-
```
step("failing step", async function() {
throw new Error('Unimplemented Step');
});
```
Or we can remove stacktrace check itself. coz we collect the screenshot anyway but not display in the report.
thoughts...?

**Comment by sriv** [comment]
irrespective of whether we check stacktrace or not, I think the stub should do the right thing and throw a JavaScript error and not an error disguised as string.
