### ISSUE TITLE
Telemetry check should use !! to check if enabled

### ISSUE THREAD

**Issue by scraymondjr** [getgauge/gauge-js#181]
Gauge sets the property as `GAUGE_TELEMETRY_ENABLED=false` if disabled and the current check of
```
if (!process.env.GAUGE_TELEMETRY_ENABLED) {
```
evaluates this to true. The check should use `!!` to check for falsey values.

```
Your Environment Information -----------
	darwin, 1.0.4, 029f328
	go (0.1.3), html-report (4.0.5), java (0.6.9), js (2.3.2), python (0.3.4), screenshot (0.0.1), spectacle (0.1.3), xml-report (0.2.0)
```

**Comment by sriv** [comment]
This was changed in 1345820fc6f5a1868375820151628b25c5fb12e9, can you please check with latest gauge-js [nightly](https://bintray.com/gauge/gauge-js/Nightly/_latestVersion)?

Perhaps some explicit logging could be of use?

If this works, we'll release gauge-js on priority.

**Comment by scraymondjr** [comment]
Ah, excellent. Pulled 2.3.3 and see it is fixed. Thank you!
