### ISSUE TITLE
Failed to initialize spec datastore.

### ISSUE THREAD

**Issue by lchrennew** [getgauge/gauge-js#183]
Expected behavior
Should be able to run specifications seamlessly

Actual behavior
Getting Use of network connection closed

Steps to replicate
1. installed gauge and chromium, specified the `GAUGE_HOME` and `TAIKO_BROWSER_PATH` to the right places
2. `npm install taiko -g`
3. `gauge install js`
4. `gauge install html-report`
5. `gauge install screenshot`
6. download examples from https://github.com/getgauge-examples/js-taiko
7. go into the folder where the examples located and `gauge run`
NOTE: taiko had been installed globally and has not been installed in the example folder,  command line `taiko -v` and `gauge version` both work.

Observe the error Failed to initialize spec datastore. Error: write tcp 127.0.0.1:37179->127.0.0.1:39668: use of closed network connection

OS: CentOS 7 (Official Docker Image)

**Comment by sriv** [comment]
Can you see if running `npm link taiko` before running `gauge run specs` helps?

**Comment by lchrennew** [comment]
> Can you see if running `npm link taiko` before running `gauge run specs` helps?

Thank you very much! It works!

**Comment by lchrennew** [comment]
And `export NODE_PATH=` works too.
