### ISSUE TITLE
Stacktrace should give the line number of the implementation file and line number details

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-js#184]
**Expected behavior**
Stacktrace should give the line number of the implementation file and line number details

**Actual behavior**
The stacktrace does not contain the  implementation file and line number details of failure

**Steps to replicate**
* Open gauge-lsp-tests
* Change the implementation of step 
```
step('generate concept <name> in new file under <path> and verify', async function (name, relativePath) {
	var response = await _customLSP.generateNewConcept(name, relativePath);
	var conceptFile = _fileExtension.getUri(_customLSP.conceptFilePath(relativePath))
	_assert.ok(response.changes[conceptFile]);
	_assert.equal(response.changes[conceptFile][0].newText, "");
});
```
* Run scenario `Should generate new Concept files` from the IDE
> The stacktrace does not contain the implementation file details
```
Failed Step: generate concept "name" in new file under "$specs" and verify
        Specification: c:\work\gauge\FT\gauge-lsp-tests\specifications\generateStubs\generateStubs.spec:18
        Error Message: AssertionError [ERR_ASSERTION]: '# name\n* ' == ''
        Stacktrace: 
        AssertionError [ERR_ASSERTION]: '# name\n* ' == ''
```
**Version**
```
Gauge version: 1.0.4.nightly-2019-01-08
Commit Hash: 408b09f

Plugins
-------
html-report (4.0.7.nightly-2018-12-10)
js (2.3.4.nightly-2018-12-20)
```
VSCode - gauge-0.0.8.nightly-2019-01-07

**Comment by BugDiver** [comment]
This issue is not replicable anymore. Following is a stack trace which I get
```

**Comment by BugDiver** [comment]
Closing it for now. Please feel free to reopen this issue if still occurs. Provide a sample project where it can be replicated.
