### ISSUE TITLE
[Spike] Typescript support

### ISSUE THREAD

**Issue by pesoklp13** [getgauge/gauge-js#187]
It would be nice to have possibility to run tests using typescript

**Comment by nehashri** [comment]
This feature is worth doing a spike. We will see if it will be useful.
In the meantime if you are interested to explore Babel with Gauge, check this issue https://github.com/getgauge/gauge-js/issues/168

**Comment by pesoklp13** [comment]
It's nice, if I can help in some way jsut, let me know.

**Comment by BugDiver** [comment]
@rightisleft @alexsad I have created gauge typescript plugin (with decorators support).
Please try it out and give some feedback so that we can improve the plugin.
To get started refer the https://bugdiver.github.io/gauge-ts/#/

**Comment by zabil** [comment]
this is now available and working well to get started run
```
gauge init ts
```

**Comment by h2grover** [comment]
https://github.com/getgauge/gauge-js/issues/187#issuecomment-498173784

@zabil @BugDiver is https://bugdiver.github.io/gauge-ts/#/ this a private plugin or it is supported by getguage team?

**Comment by zabil** [comment]
This plugin will move to https://github.com/getgauge soon.
