### ISSUE TITLE
The JS plugin should not send telemetry data during runs.

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge-js#195]
The telemetry information should only be sent when Gauge is started in daemon mode (i.e., during authoring). Gauge JS is currently sending information while gauge run is started. This needs to be removed.

**Comment by Debashis9012** [comment]
Observation after fix:
1. Telemetry information only sent when gauge is started with daemon mode.
2. Gauge js not sending information while gauge run is started.
base on the above observation this issue has been verified and fixed.

Tested version: ```2.3.5.nightly-2019-05-15```
