### ISSUE TITLE
init doesn't add @getgauge/cli

### ISSUE THREAD

**Issue by worc** [getgauge/gauge-js#198]
running `gauge init js` does a few iffy things, but mostly it creates a project that doesn't run on a `gauge is not a command` error.

shouldn't there be a `@getgauge/cli` listed as dependency so that the project and example spec can run?

**Comment by sriv** [comment]
The `gauge is not a command` error is strange, because the project itself was created with `gauge init js`, which is a `gauge` command.

The reason the template does not include this is precisely this. `gauge` is a pre-requisite to initialize a gauge project, hence it is assumed that gauge is installed. 

Real world projects can choose to include `@getgauge/cli` as a dependency to aid a `git clone` -> `run specs` workflow.

Does this make sense?

**Comment by worc** [comment]
it does, but generally i'm trying to avoid global installs. you can init a project by npm or yarn installing the gauge cli locally, and running `yarn run gauge init js` or `npm run gauge init js`. but in that case the package.json is overwritten and gauge cli is uninstalled.

my use-case was trying to add gauge/taiko to an existing project and i was hoping that using init would append a gauge/taiko configuration without overwriting the package.json. the docs are a little sparse on what exactly gauge needs to run, configuration-wise. so running init seemed like a good place to start to see a default configuration.

but it turns out `init` really is assuming an *initial* setup. so maybe this workflow isn't a good fit for init and should go under another command?

**Comment by sriv** [comment]
> my use-case was trying to add gauge/taiko to an existing project and i was hoping that using init would append a gauge/taiko configuration without overwriting the package.json.

> but it turns out init really is assuming an initial setup. so maybe this workflow isn't a good fit for init and should go under another command?

Ah, well `gauge init` is supposed to be used for a fresh project initialization.

> the docs are a little sparse on what exactly gauge needs to run, configuration-wise. 

This is exactly the kind of feedback we seek. If you have any pointers on which parts of the documentation were unclear or missing information, we'd be happy to make things explicit. Better yet, I encourage you to help improve the documentation by submitting pull requests!
