### ISSUE TITLE
Unable to install Gauge Js plugin and Taiko

### ISSUE THREAD

**Issue by Hari2019** [getgauge/gauge-js#205]
Hello Gauge JS Support,

I tried to install JS Plugin of Gauge using "**Gauge install JS**" command on windows 10 machine with in my enterprise and it does not let me install. The error I get is as follows:

C:\Users\hadusumi>gauge install js
Failed to install plugin 'js'.
Reason: Invalid plugin. Could not download js-install.json file.
Failed to install plugin 'js'.
Reason: Invalid plugin. Could not download js-install.json file.
C:\Users\hadusumi>gauge install js --version 2.1.0
Failed to install plugin 'js'.
Reason: Invalid plugin. Could not download js-install.json file.
Failed to install plugin 'js'.
Reason: Invalid plugin. Could not download js-install.json file.

Please let me know which port or url do I need to access in order to have this installation completed successfully, so that, I can go an instruct my admin or network admins to allow me to access specific urls for the installation to complete successfully.

I have in the past been able to install other guage plugins using the offline installation. The existing gauge plugins  I have are as below:
C:\Users\hadusumi>gauge -v
Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
csharp (0.10.5)
dotnet (0.1.2.nightly-2019-02-14)
html-report (4.0.7)
java (0.6.9)
screenshot (0.0.1)

2. ===================================================
I also wanted to install taiko using npm, but I get the following error:

C:\Users\hadusumi>npm install -g taiko
[..................] / rollbackFailedOptional: verb npm-session 97014244531bdfc9

and it just hangs. 

Help is very much appreciated, as we would like to start using taiko with gauge within our enterprise.

Thanks,
Hari

**Comment by zabil** [comment]
This happens when enterprises uses proxy servers to manage internet connections.
Please set the following environment variable with the right proxy settings on the cmd windows before running the commands

```
set HTTP_PROXY=http://username:password@10.0.2.2:5678
```

**Comment by Hari2019** [comment]
Hi Zabil,

Thank you for your response. Unfortunately, due to security restrictions, we cannot obtain the Proxy server user name, password and the IP address. Is there any other work around that you can suggest ? Any way to do an offline installation ?

Thanks,
Hari

**Comment by Apoorva-GA** [comment]
@Hari2019 One option is to whitelist the `npm registry`.
Also one more thing to note is taiko tries to download the chromium so you can set `TAIKO_SKIP_CHROMIUM_DOWNLOAD` env to `true`.

**Comment by shane51** [comment]
Same issue. 
Hope there is a solution for the Enterprise Proxy Server Scenario, since some companies will has the security restrictions. Currently it stops us to adopt Gauge. @zabil 
I'll be appreciate gauge has a solution for it.
Thanks

**Comment by zabil** [comment]
@shane51 In your case you can download the [offline zip](https://github.com/getgauge/gauge-js/releases) version to try the [offline installation](https://docs.gauge.org/latest/installation.html#offline-installation-of-plugins). However, you still have to white list the npm registry. There's no easy way to package all the npm modules dependency into a gauge installer.

**Comment by shane51** [comment]
@zabil  thank you, it works with offline packages
