### ISSUE TITLE
gauge.screenshot(filePath) not passing arguments to gauge_screenshot

### ISSUE THREAD

**Issue by adamdharrington** [getgauge/gauge-js#219]
This would impact anyone trying to set a specific screenshot path or name and requires changes in:

- src/custom-screenshot-registry.js
- src/gauge-global.js
- src/screenshot.js

**Comment by shubhamsc** [comment]
@adamdharrington Gauge doesn't support to pass filepath as a parameter while taking a screenshot like `gauge.screenshot(filepath)`. You can simply use `gauge.screenshot()` to take a screenshot and customize the screenshot with using [custom screenshot](https://docs.gauge.org/latest/writing-specifications.html#taking-custom-screenshots).

**Comment by adamdharrington** [comment]
IMO that contradicts how src/screenshot.js already accepts an argument in the default screenshot fn. This change simply makes opens the existing interface, there was just no way to get the argument to it. Or we could remove the tmpFile arg if it was never going to work?

Those tests for screenshot weren't testing anything before fyi, they'll pass in any circumstances right now.

**Comment by shubhamsc** [comment]
> IMO that contradicts how src/screenshot.js already accepts an argument in the default screenshot fn. This change simply makes opens the existing interface, there was just no way to get the argument to it. Or we could remove the tmpFile arg if it was never going to work?

For now, the tmpFile as a argument is never used. You can update the PR for that.

**Comment by BugDiver** [comment]
@adamdharrington We do not want to pass args to `gauge.screenshot` API for these following reasons:
* To make API's consistent with other runners
* In case of custom screenshot function, the function is expected to return a bas64 string, and not write into the file.

> IMO that contradicts how src/screenshot.js already accepts an argument in the default screenshot fn.

I would say that is totally unintentional, and just a mistake. You can update your PR (#220 )removing that argument.

**Comment by adamdharrington** [comment]
That makes sense. I will close the pull request and this issue for now anyway, thanks for the detailed reply!
