### ISSUE TITLE
Datastore functionality does not work

### ISSUE THREAD

**Issue by Debashis9012** [getgauge/gauge-js#227]
**Excepted Result**
Using datastore functionality we should able to share data in scenario, spec and suite level.

**Actual Result**
Datastore functionality does not work. While fetching key, value is showing as null.
Kindly find the below console output:
```
Running tool: gauge run /Users/js2/specs/example copy.spec --simple-console --hide-suggestion
(node:5326) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
# Specification Heading
  ## Vowel counts in single word
Key value in scenario level is null
  ## Vowel counts in multiple word
Key value in scenario level is null
Key value in spec level is null

Key value in suite lavel is null
Successfully generated html-report to => /Users/js2/reports/html-report/index.html
Specifications:	1 executed	1 passed	0 failed	0 skipped
Scenarios:	2 executed	2 passed	0 failed	0 skipped

Total time taken: 41ms
Success: Tests passed.
```

**Tested version:**
```
Gauge version: 1.0.6.nightly-2019-07-19
Commit Hash: c215a9f
Plugins
-------
js (2.3.6.nightly-2019-07-22)
```

**Comment by sriv** [comment]
@Debashis9012 please share the spec and implementation used to check this. Datastores can fetch only values that are written previously.

**Comment by BugDiver** [comment]
This issue happens with gauge-js. When we add a key-value in `beforeScenario` and try to access it in `afterScenario`.

In gauge-js the data stores are being cleared even before running the After* hooks.
The issue is at https://github.com/getgauge/gauge-js/blob/master/src/message-processor.js#L119-L122

**Comment by BugDiver** [comment]
Might be related to https://github.com/getgauge/gauge-js/issues/227
