### ISSUE TITLE
Better handling of secrets/credentials in specs

### ISSUE THREAD

**Issue by pserwylo** [getgauge/gauge-js#242]
(Forgive me if this is better suited to the gauge or taiko projects).

We require the ability to provide secrets/credentials to our tests. The way it must be done now is cumbersome in that it will result in testers having to manage a large number of undocumented files in order to understand how to make tests run.

## Current process for externalising credentials

(To the best of my knowledge)

Right now the only real way to do this is via special file parameters:

 * Log in with `<file:username.txt>` and `<file:password.txt>`

This works, but it requires a bunch of things to happen:
 * The filenames need exist for the test to run.
 * Therefore our CI (e.g. Jenkins) needs to store one different secret/credential for each file.
 * The files can't be stored in version control (if they were, then the test would fail, but not the good kind where it crashes out and says "file username.txt doesn't exist").
 * The best I can think of in terms of documenting what files need to be filled in for any new user who wants to run the tests is to have a `username.txt.example` and `password.txt.example` file, which contain text explaining what each file should contain. The devs/testers would then need to make a copy of each file in order to make the tests run.

As the number of tests grow, the number of required files may grow large too.

## An ideal process for externalising credentials

Compare this with a more typical workflow, where the secrets are externalised into a single (or even multiple) properties files. You would end up with a single properties file (e.g. `credentials.properties`, with a version `credentials.properties.example` checked into source control):

```
# This is the same username you use to login to the test environment.
USERNAME=

# This is your 16 digit pin you use to log in to the test environment.
PASSWORD=
```

Upon checking out the tests, one need only copy the example file and fill in the relevant fields.

With this, we are able to:
 * Keep track of all the required credentials in one place.
 * Document the variables.
 * CI can inject environment variables without touching these files.

## Workaround

One workaround I was playing with was to write specs like this:

* Log as `"USERNAME"` with password `"PASSWORD"`

The parameters are treated like normal string parameters. Then in my test, instead of this:

```
step("Login as <username> with password <password>", async (username, password) => {
    await write(username);
    ...
});
```

We can do the following:

```
// Look for SCREAMING_SNAKE_CASE and if so, assume it is an environment variable. 
const value = (variableFromStep) => {
    if (variableFromStep.match(/^[A-Z0-9_]*$/)) {
        if (!process.env.hasOwnProperty(variableFromStep)) {
            console.error(`Could not find the value for "${variableFromStep}". Make sure you have a file in "env/default/user.properties" and that it contains the line "${variableFromStep} = ...`);
        }
        return process.env[variableFromStep];
    }

    return variableFromStep;
};

step("Login as <username> with password <password>", async (username, password) => {
    await write(value(username));
    ...
});
```

## A better workaround?

The guage-java project [supports custom parameter handling](https://github.com/getgauge/gauge-java/issues/140) which is exactly what I've done above. The only difference is that they don't need to manually pass each of their parameters to a function (in the example above `value(...)`) because it happens automatically.

## A better-better workaround?

https://github.com/getgauge/gauge/issues/643 (Ability to protect password in specs) discusses the prospect of an `<env:...>` special parameter. While I agree that adding extra syntax to what is supposed to be a human readable and writable Markdown file is undesirable, this still seems like the best solution (because we're going to be using `<file:...>` anyway).

**Comment by negiDharmendra** [comment]
@pserwylo There is a similer [issue](https://github.com/getgauge/gauge/issues/1395) to tracke this feature. You might want to put your thoughts on that issue.

**Comment by pserwylo** [comment]
Thanks for the link @negiDharmendra. After reading there, I'm coming around to the idea of [reading environment variables from the test rather than the spec](https://github.com/getgauge/gauge/issues/1395#issuecomment-493739570). But it is hard to say what will work best for our dev + QA teams. I suppose I can try my workaround above and also the approach were the specs don't even mention environment variables or files, and time will tell which we tend to prefer.

**Comment by nehashri** [comment]
@pserwylo Please do let us know what works better for you. As of now, I am closing this issue but feel free to put a note on this issue or on https://github.com/getgauge/gauge/issues/1395 with your thoughts or approach you prefer. Thank you.
