### ISSUE TITLE
Path issue when importing module

### ISSUE THREAD

**Issue by emlaver** [getgauge/gauge-js#246]
When trying to import `uuid` in our nodejs code base, I get a `Trace: Error: Cannot find module '/home/gradle/tests/uuid/v4'` error.

After discussing with my team, we believe the issue has to with https://github.com/getgauge/gauge-js/blob/master/src/req-manager.js#L34.
It seems that an error will be thrown for anything where `modname !== path.basename(modname)`, like `uuid/v4` in our case.

We are using the workaround `const uuidv4 = require('../node_modules/uuid/v4');` for the time being.

**Comment by BugDiver** [comment]
@emlaver Thanks for reporting the issue. We could replicate this at our end, and will try to fix it soon.

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed.
Tested version: `js (2.3.6.nightly-2019-10-01)`

**Comment by h2grover** [comment]
@Debashis9012 is this fix deployed yet?
