### ISSUE TITLE
Offline installation - Failed to install plugin 'js'

### ISSUE THREAD

**Issue by manavghaigithub** [getgauge/gauge-js#250]
I saw a note few days back mentioning that JS plugin can be now installed completely offline. Is this true?

If yes, then i tried to install and below is the message i am getting.

gauge install js --file gauge-js-2.3.5.zip
Failed to install plugin 'js'.
Reason: exit status 1
Failed to install plugin 'js'.
Reason: exit status 1

--Gauge Version
gauge -v
Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
No plugins found
Plugins can be installed with `gauge install {plugin-name}`

**Comment by negiDharmendra** [comment]
@manavghaigithub offline installation is only available in a separate [nightly version](https://bintray.com/gauge/gauge-js/download_file?file_path=gauge-js-offline-2.3.6.nightly-2019-09-26.zip).
You can download the JS runner with offline installation feature from [here](https://bintray.com/gauge/gauge-js/Nightly/2.3.6.nightly-2019-09-26). 

---
**Note : The offline JS runner does not work with nodejs version below `10.10.0`**

**Comment by negiDharmendra** [comment]
@manavghaigithub Are you able to install GaugeJS runner offline?

**Comment by negiDharmendra** [comment]
@manavghaigithub Please feel free to reopen the issue if it's not resolved.
