### ISSUE TITLE
hung gauge execution because of screenshot_on_failure=false

### ISSUE THREAD

**Issue by h2grover** [getgauge/gauge-js#276]
### Environment
Device 1
- OS: MacOs
- Version: 10.14

Device 2
- OS: Ubuntu
- Version: 16 and 18 LTS

### Describe the bug
One can see the hung gauge process when default value `screenshot_on_failure = false` is used in `env/default/default.properties`. But same code gets executed properly if I set the `screenshot_on_failure = true`

### Steps to reproduce the issue
https://github.com/h2grover/demo-test-gauge

**Comment by Debashis9012** [comment]
@h2grover Earlier we have faced same kind of [issue](https://github.com/getgauge/gauge-js/issues/249) and given fix . Can we know which version of gauge-js plugin you are using ?
Latest release of gauge-js plugin you can download it form [here](https://github.com/getgauge/gauge-js/releases/tag/v2.3.6).
Could you please try with the latest release version and let us know if you are still facing the same issue.

**Comment by h2grover** [comment]
@Debashis9012 I checked locally (used `gauge install js`) and it was working fine but on the remote machine, while using `yarn install` I can still see the js version `2.3.5`. Is this version not available yet in the npm registry?

**Comment by h2grover** [comment]
I cannot see any changes in the `package-lock.json`

**Comment by zabil** [comment]
The gauge js plugin is not downloaded from npm but from releases at https://github.com/getgauge/gauge-js/releases

Try uninstalling the package and installing it again making sure it downloads the latest version.

**Comment by h2grover** [comment]
Dupe https://github.com/getgauge/gauge-js/issues/249 closing this issue for now.
But I am facing this issue https://github.com/getgauge/gauge-js/issues/271 on `2.3.6`
