### ISSUE TITLE
Extend syntax - step implementation documentation with Promise handling guide

### ISSUE THREAD

**Issue by vmatyusGitHub** [getgauge/gauge-js#279]
This will be a documentation problem.
Here is described what to do when we want to do with async tests:
https://github.com/getgauge/gauge-js/blob/master/docs/syntax/step-implementation.md#handling-assertions-and-errors-in-async-tests
I would like to request to extend the chapter with what to do when we want to assert a resolved Promise.
Here is a small code snippet from me:
```
gauge.step("I am run promise and may fail", function (done) {
    promise1.then(function(value) {
        assert.equal(true, false)
        done()
    });
    promise1.catch(function(e) {
        done(e)
    });
});
```
Otherwise there will be time out exception.

**Comment by nehashri** [comment]
@vmatyusGitHub The docs you have mentioned is outdated, we will remove this version of docs soon. Please see https://docs.gauge.org for latest documentation of Gauge.

**Comment by vmatyusGitHub** [comment]
Do not remove it please, there will be no other source to do this. Could you please refer me a similar case in the official gauge documentation. I could not find it.

**Comment by nehashri** [comment]
@vmatyusGitHub https://docs.gauge.org/?language=javascript&ide=vscode should have all documentation related to Gauge.

**Comment by vmatyusGitHub** [comment]
It will be really useful to have language specific syntax included into the official documentation. Thank you for your help.
