### ISSUE TITLE
Can't retrieve 'false' value from gauge.dataStore.scenarioStore 

### ISSUE THREAD

**Issue by rickmeier1** [getgauge/gauge-js#280]
If you try to store a 'false' value in the data store you will not be able to retrieve it. The returned value is always null.

    gauge.dataStore.scenarioStore.put('test', false);
    const storedValue = gauge.dataStore.scenarioStore.get('test');
    assert.equal(storedValue, false);

Results:
        Error Message: AssertionError [ERR_ASSERTION]: null == false
        Stacktrace: 
        AssertionError [ERR_ASSERTION]: null == false

**Comment by shubhamsc** [comment]
@rickmeier1 In gauge datastore when we do not set any value or set an empty string as a value, it set default value as null.
https://github.com/getgauge/gauge-js/blob/master/src/data-store-factory.js#L10
In javascript `"" == false` is `true`. In this case, you need to set value in a string like `gauge.dataStore.scenarioStore.put('test', 'false');`

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed. 
Tested version: `3385ae0`
