### ISSUE TITLE
Gauge spec file looses step implementation when implementation.js file opened

### ISSUE THREAD

**Issue by dspak-pub** [getgauge/gauge-js#315]
Using gauge 1.0.7 with dotnet (0.1.2.nightly-2019-02-14),html-report (4.0.7), js (2.3.8), json-report (0.3.2), screenshot (0.0.1), xml-report (0.2.1) in VS code.  
Can open and run gauge spec file fine until opening the related js implementation file then the spec lines show as having no implementation code.  Issue not seen when downgrading to js 2.3.7.

**Comment by zabil** [comment]
Do you see this issue after upgrading to 2.3.10 of gauge-js?

**Comment by dspak-pub** [comment]
No, the same issue is not present with the 2.3.10 version.
