### ISSUE TITLE
Unable to SetReadDeadLine on runner: set tcp 127.0.0.1:51101: use of closed network connection

### ISSUE THREAD

**Issue by windyliu1118** [getgauge/gauge-js#320]
I missed one step to navigate to position page in the spec, so it will not find the element Add position in current page, so the test will fail. But when running the test, the log has error info but the browser is not closed.
Error is as below:
```
# 01 Positions
  ## Verify applicant can sign the documents in hiring process   ✔0
0
Error: Button with label Add position  not found
at findElements (/Users/windyliu/Workstream/workstream-auto/node_modules/taiko/lib/elementSearch.js:271:11)
at <anonymous>
Error ----------------------------------
[Gauge]
Unable to SetReadDeadLine on runner: set tcp 127.0.0.1:51101: use of closed network connection
Get Support ----------------------------
        Docs:          https://docs.gauge.org
        Bugs:          https://github.com/getgauge/gauge/issues
        Chat:          https://spectrum.chat/gauge
Your Environment Information -----------
        darwin, 1.0.7, ed7b4fd6
        html-report (4.0.9), js (2.3.7), screenshot (0.0.1), xml-report (0.2.3)
```

**Comment by sriv** [comment]
gauge-js needs to handle errors that arise from user code.

**Comment by NivedhaSenthil** [comment]
@windyliu1118 are you seeing this happen consistently... will be really helpful if you can help us setup a sample to reproduce this issue

**Comment by zabil** [comment]
Closing this for now as it may have been fixed in the newer releases. Will re-open it if it is still there and there is a way to reproduce this error.
