### ISSUE TITLE
Unable to add JS webdriver for gauge.

### ISSUE THREAD

**Issue by cnagadya** [getgauge/gauge-js#338]
When I run `$ gauge init js_webdriver` as stated in the documentation, I get the error below
![image](https://user-images.githubusercontent.com/26176338/80196171-4e0efc80-861d-11ea-8553-e9c5ceb1bc5a.png)

**Comment by sriv** [comment]
`js_webdriver` is not a template - please, can you point to the section in docs where you saw this recommended? We'll need to fix that.

In order to see list of templates available, please run `gauge init -t`. You can then pass one of the template names to `gauge init`.

**Comment by cnagadya** [comment]
In the [readme](https://github.com/getgauge/gauge-js/blob/master/README.md). Same case for Puppeteer
