### ISSUE TITLE
multi-threads for js runner

### ISSUE THREAD

**Issue by roughsoft** [getgauge/gauge-js#388]
Node 10 shipped with worker-threads, a "threading API" that uses SharedArrayBuffers to communicate between the main process and its child threads. This experimental Node feature can significantly improve the communication time between parent and child processes.
we can ref:
https://github.com/facebook/jest/blob/master/packages/jest-worker/README.md

**Comment by sriv** [comment]
thanks, this is something we've been considering as well.

**Comment by roughsoft** [comment]
@zabil ,yesterday I read the code ,I found the communication between gauge and language runner is through gRPC ,we know gRPC support deployment server and client crossing the two machines, so why not refactor the runner code connecting the remote gauge by url

**Comment by sriv** [comment]
I believe your last comment is relevant to https://github.com/getgauge/gauge/issues/1743. Can we discuss this over there please?
