### ISSUE TITLE
AfterSuite hook receives a "null" context value

### ISSUE THREAD

**Issue by manasi-rk** [getgauge/gauge-js#395]
**Expected :**
afterSuite(async (context) => {
   console.log(context); // This should give the appropriate context value.
    await closeBrowser();
});

**Actual :** 
context value received in the afterSuite is null.

**Comment by sriv** [comment]
The execution context does not have anything related to the suite at the moment. What information are you looking for in `afterSuite` @manasi-rk ?

**Comment by manasi-rk** [comment]
I was expecting that the AfterSuite hook can contain some execution info or the suite info
currentExecutionInfo 
gauge.messages.ProtoSuiteResult suiteResult 
or these infos
 /// Holds the project name
    string projectName = 5;
    /// Holds the command line arguments.
    repeated ExecutionArg ExecutionArgs = 6;
    /// Holds the number of running execution streams.
    int32 numberOfExecutionStreams = 7;
    /// Holds the runner id for parallel execution.
    int32 runnerId = 8; /// Holds the project name
    string projectName = 5;
    /// Holds the command line arguments.
    repeated ExecutionArg ExecutionArgs = 6;
    /// Holds the number of running execution streams.
    int32 numberOfExecutionStreams = 7;
    /// Holds the runner id for parallel execution.
    int32 runnerId = 8;

**Comment by sriv** [comment]
The context does not have suite result, but [other metadata](https://github.com/getgauge/gauge-proto/blob/master/messages.proto#L128-L136) should be available.

Nevertheless, the context should not be null. I was curious if you were expecting something that gauge does not pass as part of execution context.

**Comment by NivedhaSenthil** [comment]
Fix should be available in next gauge release 1.1.5
