### ISSUE TITLE
Unable to install Gauge Js plugin

### ISSUE THREAD

**Issue by logyourtesting** [getgauge/gauge-js#549]
Hello Gauge JS Support,
I tried to install JS Plugin of Gauge using "Gauge install JS" command on windows 10 machine with in my enterprise and it does not let me install. The error I get is as follows:
**From cmd**
Failed to install plugin 'js'.
Reason: invalid character '<' looking for beginning of value

**From Visual studio code**
Installing gauge js plugin ...

Failed to install plugin 'js'.
Reason: invalid character '<' looking for beginning of value

Environment Information -----------
	windows, 1.4.2, f080fbc
	Could not retrieve plugin information.

**Comment by zabil** [comment]
Looks like you are behind a proxy server. Please make you've updated your [proxy settings](https://docs.gauge.org/configuration.html?os=macos&language=python&ide=vscode#http-proxy-setting-while-using-gauge) to work with the command line

**Comment by logyourtesting** [comment]
@zabil I updated proxy settings and its working for me 
Thanks you so much for Quick reply.
