### ISSUE TITLE
Unable to install Gauge Js plugin on mac

### ISSUE THREAD

**Issue by AliyeSimsek** [getgauge/gauge-js#550]
Hello Gauge JS Support,
I tried to install JS Plugin of Gauge using "gauge install js" command on a mac, but it does not let me install. Other Plugins like  html-report or screenshot could be installed.
The error I get is as follows:

Failed to install plugin 'js' version 2.4.0.
Reason: exit status 1

Environment Information -----------
macOS Monterey Version 12.1
Gauge version: 1.4.2
Node Version: v16.13.1

**Comment by sriv** [comment]
can you please try running `gauge install js -l debug` and check the output?

on my mac machine, I can see this line:

```
Downloading https://downloads.gauge.org/plugin/js?l=&p=dotnet,go,html-report,inprogress,java,js,python,ruby,screenshot,ts,xml-report&o=darwin&a=arm64
```

And if you then try to `curl` that url you should see the content of https://github.com/getgauge/gauge-repository/blob/master/js-install.json

Could you please check?

**Comment by AliyeSimsek** [comment]
for both comands `gauge install js --log-level debug` and `gauge install js -l debug`
i am getting this output:

Gathering metadata for js
Downloading https://downloads.gauge.org/plugin/js?l=&p=&o=darwin&a=amd64
Downloading https://github.com/getgauge/gauge-js/releases/download/v2.4.0/gauge-js-2.4.0.zip
.......................
Running plugin hook command => [npm install --production --silent]
Failed to install plugin 'js' version 2.4.0.
Reason: exit status 1

**Comment by sriv** [comment]
what version of node and npm do you have installed?

**Comment by AliyeSimsek** [comment]
The node version is v16.13.1 and the npm version is 8.1.2

**Comment by sriv** [comment]
can you please try this:

1. download and extract https://github.com/getgauge/gauge-js/releases/download/v2.4.0/gauge-js-2.4.0.zip
2. `cd gauge-js-2.4.0  && npm install --production`

It looks like npm install failed for some reason, this may give some hints

**Comment by AliyeSimsek** [comment]
Thanks a lot :)
