### ISSUE TITLE
NodeJs 16 Gauge-JS plugin installation takes an hour of time in Ubuntu Container

### ISSUE THREAD

**Issue by tamnl** [getgauge/gauge-js#573]
Gauge-js plugin installation is taking almost an hour time to perform installation in Ubuntu container. 

**To Reproduce**
Steps (or project) to reproduce the behavior:
1. install the Gauge tool 
2. install the gauge-js plugin 
3. Taking almost an hour to complete installation

Version of plugin
Node-js 16.18.1
gauge-js 2.4.0

PS: Tried to download 2.4.2 version of gauge-js plugin from the current release but not able to find the plugin only source code.zip is available.

**Comment by zabil** [comment]
You can find build from source instructions at

https://github.com/getgauge/gauge-js#build-from-source

**Comment by chadlwilson** [comment]
@tamnl I could not replicate this, installed fine for me:

```
root@a187b38ebbe2:/# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
root@a187b38ebbe2:/# node -v
v16.20.1
root@a187b38ebbe2:/# time gauge install js
.....................
Successfully installed plugin 'js' version 2.4.0

real	0m7.664s
user	0m1.941s
sys	0m0.628s
root@a187b38ebbe2:/# gauge -v
Gauge version: 1.5.1
Commit Hash: bdc0f73

Plugins
-------
js (2.4.0)
```

You might want to check your environment, network access etc as I cannot reproduce the above. If you can provide additional information on how to recreate this, we can re-open, but I don't think there is a problem here.

PS: `2.4.2` was a partially completed release which failed part-way through, I have cleaned it up now.
